on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Github Pages
    steps:
      - name: Checkout template repo
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          repository: snowplow-incubator/accelerator-web-ui-template 

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Move the content folder
        run: |
          mv ./main/content .
      - name: Replace configuration placeholders
        env:
          TITLE: Accelerators Template
          DESCRIPTION: Tutorial for setting up a Snowplow Accelerator
          BASE_URL: https://snowplow-incubator.github.io/accelerator-template
          AUTHOR: Jack Keene 
          LANDING_PAGE_URL: /accelerator-template
        run: |
          sed -i 's|ACCELERATOR_TITLE|${{ env.TITLE }}|g' config.toml
          sed -i 's|ACCELERATOR_DESCRIPTION|${{ env.DESCRIPTION }}|g' config.toml
          sed -i 's|ACCELERATOR_BASE_URL|${{ env.BASE_URL }}|g' config.toml
          sed -i 's|ACCELERATOR_AUTHOR|${{ env.AUTHOR }}|g' config.toml
          sed -i 's|ACCELERATOR_LANDING_PAGE_URL|${{ env.LANDING_PAGE_URL }}|g' config.toml
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo

      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public